// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialCyclingWorld.Web.Data;

namespace SuperCyclingWorld.Web.Migrations
{
    [DbContext(typeof(SCWDbContext))]
    [Migration("20210719144354_ReseedWielrenners")]
    partial class ReseedWielrenners
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AantalRecords");

                    b.Property<Guid?>("Clubleider");

                    b.Property<string>("Clubnaam");

                    b.Property<int>("Oprichtingsjaar");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new { Id = new Guid("c54a41fd-e91c-46c2-9a28-02b355a4d0cb"), AantalRecords = 0, Clubnaam = "WTC", Oprichtingsjaar = 2001 },
                        new { Id = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), AantalRecords = 0, Clubnaam = "DCTV", Oprichtingsjaar = 2016 },
                        new { Id = new Guid("8ea09cd4-0fc2-4020-a45f-1b140284bcf5"), AantalRecords = 0, Clubnaam = "De lustige rijders", Oprichtingsjaar = 1991 },
                        new { Id = new Guid("a56b2979-fba1-40e0-899d-ab804eae28a3"), AantalRecords = 0, Clubnaam = "WTC Melsele", Oprichtingsjaar = 1966 },
                        new { Id = new Guid("aa388eb8-ac4b-4684-ab4e-f8ec3d93dcaf"), AantalRecords = 0, Clubnaam = "The master cyclists", Oprichtingsjaar = 2011 }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.ClubSupporter", b =>
                {
                    b.Property<Guid>("ClubId");

                    b.Property<Guid>("SupporterId");

                    b.HasKey("ClubId", "SupporterId");

                    b.HasIndex("SupporterId");

                    b.ToTable("ClubSupporter");

                    b.HasData(
                        new { ClubId = new Guid("8ea09cd4-0fc2-4020-a45f-1b140284bcf5"), SupporterId = new Guid("4506204b-01db-4f86-aa36-94beb740c624") },
                        new { ClubId = new Guid("c54a41fd-e91c-46c2-9a28-02b355a4d0cb"), SupporterId = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119") },
                        new { ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), SupporterId = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119") },
                        new { ClubId = new Guid("8ea09cd4-0fc2-4020-a45f-1b140284bcf5"), SupporterId = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119") },
                        new { ClubId = new Guid("a56b2979-fba1-40e0-899d-ab804eae28a3"), SupporterId = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119") },
                        new { ClubId = new Guid("aa388eb8-ac4b-4684-ab4e-f8ec3d93dcaf"), SupporterId = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119") },
                        new { ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), SupporterId = new Guid("e0cc61d4-ab25-4e49-be3f-272f5231a344") },
                        new { ClubId = new Guid("8ea09cd4-0fc2-4020-a45f-1b140284bcf5"), SupporterId = new Guid("dbe3f83c-f1dd-498b-8c5a-8f7caa3ae1d1") },
                        new { ClubId = new Guid("c54a41fd-e91c-46c2-9a28-02b355a4d0cb"), SupporterId = new Guid("4506204b-01db-4f86-aa36-94beb740c624") },
                        new { ClubId = new Guid("c54a41fd-e91c-46c2-9a28-02b355a4d0cb"), SupporterId = new Guid("e0cc61d4-ab25-4e49-be3f-272f5231a344") }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.FanRegistratie", b =>
                {
                    b.Property<Guid>("SupporterId");

                    b.Property<Guid>("WielrennerId");

                    b.HasKey("SupporterId", "WielrennerId");

                    b.HasIndex("WielrennerId");

                    b.ToTable("FanRegistratie");

                    b.HasData(
                        new { SupporterId = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119"), WielrennerId = new Guid("2c699b52-ff83-481e-8f70-215611ca4607") },
                        new { SupporterId = new Guid("dbe3f83c-f1dd-498b-8c5a-8f7caa3ae1d1"), WielrennerId = new Guid("fcdb0108-f64d-4a0d-ad1c-805337a19e42") },
                        new { SupporterId = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119"), WielrennerId = new Guid("45521d10-d277-43c9-bc3a-6244685c9a09") },
                        new { SupporterId = new Guid("4506204b-01db-4f86-aa36-94beb740c624"), WielrennerId = new Guid("2c699b52-ff83-481e-8f70-215611ca4607") },
                        new { SupporterId = new Guid("dbe3f83c-f1dd-498b-8c5a-8f7caa3ae1d1"), WielrennerId = new Guid("66da1773-c553-4450-9747-d75a68cc1dee") },
                        new { SupporterId = new Guid("e0cc61d4-ab25-4e49-be3f-272f5231a344"), WielrennerId = new Guid("fcdb0108-f64d-4a0d-ad1c-805337a19e42") }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Fiets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Merk");

                    b.Property<Guid>("WielrennerId");

                    b.Property<string>("Zadel");

                    b.HasKey("Id");

                    b.HasIndex("WielrennerId");

                    b.ToTable("Fietsen");

                    b.HasData(
                        new { Id = new Guid("0e97e06b-854b-4e55-b4cb-0b460e0c8fa1"), Merk = "B-Twin", WielrennerId = new Guid("2c699b52-ff83-481e-8f70-215611ca4607"), Zadel = "Zwart zadel" },
                        new { Id = new Guid("893c64b8-ab56-4e76-8cb3-5242081a8f79"), Merk = "Moldava", WielrennerId = new Guid("45521d10-d277-43c9-bc3a-6244685c9a09"), Zadel = "Geel zadel" },
                        new { Id = new Guid("669910d8-9f60-432a-acad-2b99145ccb30"), Merk = "Merckx", WielrennerId = new Guid("66da1773-c553-4450-9747-d75a68cc1dee"), Zadel = "Oranje zadel" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("RecordCijfer");

                    b.Property<string>("RecordEenheid");

                    b.Property<int>("RecordType");

                    b.Property<string>("Recordnaam");

                    b.Property<string>("Thropy");

                    b.Property<Guid?>("WielrennerId");

                    b.HasKey("Id");

                    b.HasIndex("WielrennerId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Rit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Aankomst");

                    b.Property<string>("Name");

                    b.Property<Guid>("PersoonId");

                    b.Property<string>("Start");

                    b.Property<Guid?>("WielrennerId");

                    b.HasKey("Id");

                    b.HasIndex("WielrennerId");

                    b.ToTable("Ritten");
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Supporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Achternaam");

                    b.Property<string>("Email");

                    b.Property<DateTime>("GeboorteDatum");

                    b.Property<string>("Paswoord");

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.ToTable("Supporters");

                    b.HasData(
                        new { Id = new Guid("98f93829-b21e-4def-a2ce-27f5dcb0f119"), Achternaam = "The Pooh", Email = "ThePooh@live.be", GeboorteDatum = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Winnie" },
                        new { Id = new Guid("4506204b-01db-4f86-aa36-94beb740c624"), Achternaam = "Van Achtmaal", Email = "VanAchtmaal@live.be", GeboorteDatum = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Thomas" },
                        new { Id = new Guid("e0cc61d4-ab25-4e49-be3f-272f5231a344"), Achternaam = "VanKerkhove", Email = "VanKerkhove@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Nico" },
                        new { Id = new Guid("dbe3f83c-f1dd-498b-8c5a-8f7caa3ae1d1"), Achternaam = "Kronenburg", Email = "Kronenburg@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Koen" },
                        new { Id = new Guid("d89c56f3-b490-40c0-b86f-61e8cec16946"), Achternaam = "Van Kruisem", Email = "VanKruisem@live.be", GeboorteDatum = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Willy" },
                        new { Id = new Guid("014e4a0f-099c-4cf7-8652-1ae9fadd53ca"), Achternaam = "Wezemaal", Email = "Wezemaal@live.be", GeboorteDatum = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Bert" },
                        new { Id = new Guid("25707fbf-fc3d-4dbc-9013-6a6e1069c1bd"), Achternaam = "Opdorp", Email = "Opdorp@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Alfons" },
                        new { Id = new Guid("6d704bd7-de74-4bb5-8afc-2ac0da45cf23"), Achternaam = "AppelGate", Email = "Appelgate@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Christina" },
                        new { Id = new Guid("c1756a14-52d0-4eca-a6fd-8e6c4254ec9a"), Achternaam = "Monroe", Email = "Monroe@live.be", GeboorteDatum = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Marlyn" },
                        new { Id = new Guid("1bc6f599-920e-418e-99b6-1864df2f0c31"), Achternaam = "Clooney", Email = "Clooney@live.be", GeboorteDatum = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "George" },
                        new { Id = new Guid("dccae4d8-f77f-47c7-b175-e75532eb9b18"), Achternaam = "Peeters", Email = "Peeters@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Jan" },
                        new { Id = new Guid("71947fce-cada-4255-b823-819808d8a2d1"), Achternaam = "Reyns", Email = "Reyns@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Rita" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Wielrenner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AantalRecords");

                    b.Property<string>("Achternaam");

                    b.Property<Guid>("ClubId");

                    b.Property<string>("Email");

                    b.Property<DateTime>("GeboorteDatum");

                    b.Property<double>("GemiddeldKm_h");

                    b.Property<int>("GemiddeldeKM_Rit");

                    b.Property<string>("Paswoord");

                    b.Property<int>("TotaalAantalGeredenKilometers");

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Wielrenners");

                    b.HasData(
                        new { Id = new Guid("66da1773-c553-4450-9747-d75a68cc1dee"), AantalRecords = 0, Achternaam = "Franckaert", ClubId = new Guid("a56b2979-fba1-40e0-899d-ab804eae28a3"), Email = "Franckaert@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 31.0, GemiddeldeKM_Rit = 10, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 100, Voornaam = "Robin" },
                        new { Id = new Guid("2c699b52-ff83-481e-8f70-215611ca4607"), AantalRecords = 0, Achternaam = "Jansma", ClubId = new Guid("8ea09cd4-0fc2-4020-a45f-1b140284bcf5"), Email = "Jansma@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 32.0, GemiddeldeKM_Rit = 20, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 101, Voornaam = "Johanna" },
                        new { Id = new Guid("45521d10-d277-43c9-bc3a-6244685c9a09"), AantalRecords = 0, Achternaam = "Vissers", ClubId = new Guid("c54a41fd-e91c-46c2-9a28-02b355a4d0cb"), Email = "Vissers@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 33.0, GemiddeldeKM_Rit = 30, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 102, Voornaam = "Bert" },
                        new { Id = new Guid("fcdb0108-f64d-4a0d-ad1c-805337a19e42"), AantalRecords = 0, Achternaam = "Depardieu", ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), Email = "Depardieu@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 34.0, GemiddeldeKM_Rit = 40, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 103, Voornaam = "Gerard" },
                        new { Id = new Guid("1e0a59b4-ccfb-4248-be73-2ba20811626e"), AantalRecords = 0, Achternaam = "Van Overmeire", ClubId = new Guid("a56b2979-fba1-40e0-899d-ab804eae28a3"), Email = "VanOvermeire@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 35.0, GemiddeldeKM_Rit = 50, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 104, Voornaam = "Marc" },
                        new { Id = new Guid("f020bee2-8a96-47c7-b7ea-7892bf879151"), AantalRecords = 0, Achternaam = "Camara", ClubId = new Guid("c54a41fd-e91c-46c2-9a28-02b355a4d0cb"), Email = "Camara@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 36.0, GemiddeldeKM_Rit = 60, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 105, Voornaam = "Herdy" },
                        new { Id = new Guid("824d5ced-ab37-4a7e-bcc6-061e22d4a326"), AantalRecords = 0, Achternaam = "Donckerwolcke", ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), Email = "Donckerwolcke@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 37.0, GemiddeldeKM_Rit = 70, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 106, Voornaam = "Thomas" },
                        new { Id = new Guid("a0316ff8-babf-4fd1-be40-d988084b5f01"), AantalRecords = 0, Achternaam = "Garnaal", ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), Email = "Garnaal@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 38.0, GemiddeldeKM_Rit = 80, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 107, Voornaam = "Sofie" },
                        new { Id = new Guid("53385228-5f07-4850-a42b-bb00f55a554c"), AantalRecords = 0, Achternaam = "Brokkenpap", ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), Email = "Brokkenpap@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 39.0, GemiddeldeKM_Rit = 90, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 108, Voornaam = "Berend" },
                        new { Id = new Guid("749a8780-6a86-4d26-bdd9-fed2ae7e46f7"), AantalRecords = 0, Achternaam = "Mega", ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), Email = "Mega@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 40.0, GemiddeldeKM_Rit = 5, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 109, Voornaam = "Mindy" },
                        new { Id = new Guid("d10fa0eb-7794-40ea-9b06-68ac7dbe36be"), AantalRecords = 0, Achternaam = "Scarlet", ClubId = new Guid("c54a41fd-e91c-46c2-9a28-02b355a4d0cb"), Email = "Scarlet@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 41.0, GemiddeldeKM_Rit = 6, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 110, Voornaam = "Johanson" },
                        new { Id = new Guid("f0fa4b67-9704-4f79-b9b0-980644351d3a"), AantalRecords = 0, Achternaam = "Beukelaer", ClubId = new Guid("a56b2979-fba1-40e0-899d-ab804eae28a3"), Email = "Beukelaer@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 42.0, GemiddeldeKM_Rit = 7, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 111, Voornaam = "Koekjes" },
                        new { Id = new Guid("26d315d0-c4c0-43de-91fc-ee6a2c4a89e9"), AantalRecords = 0, Achternaam = "Mertens", ClubId = new Guid("aa388eb8-ac4b-4684-ab4e-f8ec3d93dcaf"), Email = "Mertens@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 43.0, GemiddeldeKM_Rit = 8, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 112, Voornaam = "Evelyne" },
                        new { Id = new Guid("6afff5e4-b757-4958-b8f2-d174a1896226"), AantalRecords = 0, Achternaam = "VanHoof", ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), Email = "Vanhoof@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 44.0, GemiddeldeKM_Rit = 9, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 113, Voornaam = "Emily" },
                        new { Id = new Guid("247493d4-ea61-444b-add0-0eccaa9c0363"), AantalRecords = 0, Achternaam = "Vanderplas", ClubId = new Guid("dbd498a7-8d0a-4115-b835-2175836fc11e"), Email = "Vanderplas@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 45.0, GemiddeldeKM_Rit = 10, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 114, Voornaam = "Sonja" },
                        new { Id = new Guid("7850aecd-ca8e-4d6d-ae73-548f581a6431"), AantalRecords = 0, Achternaam = "Bambino", ClubId = new Guid("aa388eb8-ac4b-4684-ab4e-f8ec3d93dcaf"), Email = "Bambino@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 46.0, GemiddeldeKM_Rit = 11, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 115, Voornaam = "Salvatore" },
                        new { Id = new Guid("1e7c806f-d68b-4c05-ab51-8512eca34705"), AantalRecords = 0, Achternaam = "Zalinski", ClubId = new Guid("aa388eb8-ac4b-4684-ab4e-f8ec3d93dcaf"), Email = "Zalinski@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 47.0, GemiddeldeKM_Rit = 12, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 116, Voornaam = "Wosznjeck" },
                        new { Id = new Guid("6808250e-d1c1-4908-86bf-30e3fc279ce8"), AantalRecords = 0, Achternaam = "Debruyne", ClubId = new Guid("8ea09cd4-0fc2-4020-a45f-1b140284bcf5"), Email = "Debruyne@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 48.0, GemiddeldeKM_Rit = 13, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 117, Voornaam = "Kevin" },
                        new { Id = new Guid("f127495c-7b37-4904-8aee-ecaa999ca04c"), AantalRecords = 0, Achternaam = "Hazard", ClubId = new Guid("a56b2979-fba1-40e0-899d-ab804eae28a3"), Email = "Hazard@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 49.0, GemiddeldeKM_Rit = 14, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 118, Voornaam = "Eden" },
                        new { Id = new Guid("d30689d3-ce1a-40cf-8c55-f2ad17964ff3"), AantalRecords = 0, Achternaam = "Evenepoel", ClubId = new Guid("a56b2979-fba1-40e0-899d-ab804eae28a3"), Email = "Evenepoel@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), GemiddeldKm_h = 50.0, GemiddeldeKM_Rit = 15, Paswoord = "202CB962AC59075B964B07152D234B70", TotaalAantalGeredenKilometers = 119, Voornaam = "Remco" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.ClubSupporter", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Club")
                        .WithMany("ClubSupporters")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SuperCyclingWorld.Core.Entities.Supporter")
                        .WithMany("Clubs")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.FanRegistratie", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Supporter")
                        .WithMany("Wielrenners")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner")
                        .WithMany("Wielrenners")
                        .HasForeignKey("WielrennerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Fiets", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner")
                        .WithMany("Fietsen")
                        .HasForeignKey("WielrennerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Record", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner", "Wielrenner")
                        .WithMany()
                        .HasForeignKey("WielrennerId");
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Rit", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner", "Wielrenner")
                        .WithMany("Ritten")
                        .HasForeignKey("WielrennerId");
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Wielrenner", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Club", "Club")
                        .WithMany("Leden")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
