// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialCyclingWorld.Web.Data;

namespace SuperCyclingWorld.Web.Migrations
{
    [DbContext(typeof(SCWDbContext))]
    [Migration("20210710112154_ExtraSeedWielrenners")]
    partial class ExtraSeedWielrenners
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("Clubleider");

                    b.Property<string>("Clubnaam");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new { Id = new Guid("b5477436-f388-4aea-9ade-b01b3875eaeb"), Clubnaam = "WTC" },
                        new { Id = new Guid("568c3c3a-7c30-454f-9adf-9ab8992e1a24"), Clubnaam = "DCTV" },
                        new { Id = new Guid("93664e7a-b3d7-4f51-bcc7-5ea2b622173f"), Clubnaam = "De lustige rijders" },
                        new { Id = new Guid("7696e666-3073-492d-902a-9331d25ff234"), Clubnaam = "WTC Melsele" },
                        new { Id = new Guid("cabaf72e-c69e-456b-8da9-d2c9aac86ff0"), Clubnaam = "The master cyclists" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.ClubSupporter", b =>
                {
                    b.Property<Guid>("ClubId");

                    b.Property<Guid>("SupporterId");

                    b.HasKey("ClubId", "SupporterId");

                    b.HasIndex("SupporterId");

                    b.ToTable("ClubSupporter");

                    b.HasData(
                        new { ClubId = new Guid("93664e7a-b3d7-4f51-bcc7-5ea2b622173f"), SupporterId = new Guid("fe22ed0c-074a-439d-99dc-e23522d413ff") },
                        new { ClubId = new Guid("b5477436-f388-4aea-9ade-b01b3875eaeb"), SupporterId = new Guid("a2a3ddb8-a813-4e2d-99b8-1a445f0dc7b8") },
                        new { ClubId = new Guid("568c3c3a-7c30-454f-9adf-9ab8992e1a24"), SupporterId = new Guid("611bcd8b-4bdb-4205-a46c-c1c46ab3432b") },
                        new { ClubId = new Guid("93664e7a-b3d7-4f51-bcc7-5ea2b622173f"), SupporterId = new Guid("94f3968d-0d2c-478d-9aae-4ae088b1da48") },
                        new { ClubId = new Guid("b5477436-f388-4aea-9ade-b01b3875eaeb"), SupporterId = new Guid("fe22ed0c-074a-439d-99dc-e23522d413ff") },
                        new { ClubId = new Guid("cabaf72e-c69e-456b-8da9-d2c9aac86ff0"), SupporterId = new Guid("94f3968d-0d2c-478d-9aae-4ae088b1da48") },
                        new { ClubId = new Guid("7696e666-3073-492d-902a-9331d25ff234"), SupporterId = new Guid("a2a3ddb8-a813-4e2d-99b8-1a445f0dc7b8") },
                        new { ClubId = new Guid("b5477436-f388-4aea-9ade-b01b3875eaeb"), SupporterId = new Guid("611bcd8b-4bdb-4205-a46c-c1c46ab3432b") }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.FanRegistratie", b =>
                {
                    b.Property<Guid>("SupporterId");

                    b.Property<Guid>("WielrennerId");

                    b.HasKey("SupporterId", "WielrennerId");

                    b.HasIndex("WielrennerId");

                    b.ToTable("FanRegistratie");

                    b.HasData(
                        new { SupporterId = new Guid("a2a3ddb8-a813-4e2d-99b8-1a445f0dc7b8"), WielrennerId = new Guid("4afd4726-fe31-4826-8bc5-83d7d86bb979") },
                        new { SupporterId = new Guid("94f3968d-0d2c-478d-9aae-4ae088b1da48"), WielrennerId = new Guid("6b4a60a0-a802-442a-bfc8-3cd4ddb6ac32") },
                        new { SupporterId = new Guid("a2a3ddb8-a813-4e2d-99b8-1a445f0dc7b8"), WielrennerId = new Guid("a2c030e3-0a05-4038-9aca-56889e4d0134") },
                        new { SupporterId = new Guid("fe22ed0c-074a-439d-99dc-e23522d413ff"), WielrennerId = new Guid("4afd4726-fe31-4826-8bc5-83d7d86bb979") },
                        new { SupporterId = new Guid("94f3968d-0d2c-478d-9aae-4ae088b1da48"), WielrennerId = new Guid("7de9d56a-5331-466e-a465-e3e7d5a3e5ff") },
                        new { SupporterId = new Guid("611bcd8b-4bdb-4205-a46c-c1c46ab3432b"), WielrennerId = new Guid("6b4a60a0-a802-442a-bfc8-3cd4ddb6ac32") }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Fiets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Merk");

                    b.Property<Guid>("WielrennerId");

                    b.Property<string>("Zadel");

                    b.HasKey("Id");

                    b.HasIndex("WielrennerId");

                    b.ToTable("Fietsen");

                    b.HasData(
                        new { Id = new Guid("34efc7f6-d14c-408a-b2ee-8ffba40f5434"), Merk = "B-Twin", WielrennerId = new Guid("4afd4726-fe31-4826-8bc5-83d7d86bb979"), Zadel = "Zwart zadel" },
                        new { Id = new Guid("26b3155a-4f02-465d-88f1-4d89a39c50f9"), Merk = "Moldava", WielrennerId = new Guid("a2c030e3-0a05-4038-9aca-56889e4d0134"), Zadel = "Geel zadel" },
                        new { Id = new Guid("d2481d9a-9ba0-423d-b5ab-bbbde01714d0"), Merk = "Merckx", WielrennerId = new Guid("7de9d56a-5331-466e-a465-e3e7d5a3e5ff"), Zadel = "Oranje zadel" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Supporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Achternaam");

                    b.Property<string>("Email");

                    b.Property<DateTime>("GeboorteDatum");

                    b.Property<string>("Paswoord");

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.ToTable("Supporters");

                    b.HasData(
                        new { Id = new Guid("a2a3ddb8-a813-4e2d-99b8-1a445f0dc7b8"), Achternaam = "The Pooh", Email = "ThePooh@live.be", GeboorteDatum = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Winnie" },
                        new { Id = new Guid("fe22ed0c-074a-439d-99dc-e23522d413ff"), Achternaam = "Van Achtmaal", Email = "VanAchtmaal@live.be", GeboorteDatum = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Thomas" },
                        new { Id = new Guid("611bcd8b-4bdb-4205-a46c-c1c46ab3432b"), Achternaam = "VanKerkhove", Email = "VanKerkhove@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Nico" },
                        new { Id = new Guid("94f3968d-0d2c-478d-9aae-4ae088b1da48"), Achternaam = "Kronenburg", Email = "Kronenburg@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Koen" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Wielrenner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Achternaam");

                    b.Property<Guid?>("ClubId")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<DateTime>("GeboorteDatum");

                    b.Property<string>("Paswoord");

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Wielrenners");

                    b.HasData(
                        new { Id = new Guid("7de9d56a-5331-466e-a465-e3e7d5a3e5ff"), Achternaam = "Franckaert", ClubId = new Guid("b5477436-f388-4aea-9ade-b01b3875eaeb"), Email = "Franckaert@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Robin" },
                        new { Id = new Guid("4afd4726-fe31-4826-8bc5-83d7d86bb979"), Achternaam = "Jansma", ClubId = new Guid("568c3c3a-7c30-454f-9adf-9ab8992e1a24"), Email = "Jansma@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Johanna" },
                        new { Id = new Guid("a2c030e3-0a05-4038-9aca-56889e4d0134"), Achternaam = "Vissers", ClubId = new Guid("93664e7a-b3d7-4f51-bcc7-5ea2b622173f"), Email = "Vissers@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Bert" },
                        new { Id = new Guid("6b4a60a0-a802-442a-bfc8-3cd4ddb6ac32"), Achternaam = "Depardieu", ClubId = new Guid("7696e666-3073-492d-902a-9331d25ff234"), Email = "Depardieu@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Gerard" },
                        new { Id = new Guid("7e4d4b50-8389-4095-b3b9-45b33e5c5436"), Achternaam = "Van Overmeire", ClubId = new Guid("cabaf72e-c69e-456b-8da9-d2c9aac86ff0"), Email = "VanOvermeire@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Marc" },
                        new { Id = new Guid("43648603-9ab6-4308-a3ef-6cd796e8fabe"), Achternaam = "Camara", ClubId = new Guid("b5477436-f388-4aea-9ade-b01b3875eaeb"), Email = "Camara@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Herdy" },
                        new { Id = new Guid("847666a5-65c7-4e66-bbea-0d123adc5c9f"), Achternaam = "Donckerwolcke", ClubId = new Guid("568c3c3a-7c30-454f-9adf-9ab8992e1a24"), Email = "Donckerwolcke@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Thomas" },
                        new { Id = new Guid("9abb5cd6-71fc-4c7c-957d-7778e3b873ac"), Achternaam = "Garnaal", ClubId = new Guid("93664e7a-b3d7-4f51-bcc7-5ea2b622173f"), Email = "Garnaal@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Sofie" },
                        new { Id = new Guid("b413ba62-936b-4863-8685-562a6cd78038"), Achternaam = "Brokkenpap", ClubId = new Guid("7696e666-3073-492d-902a-9331d25ff234"), Email = "Brokkenpap@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Berend" },
                        new { Id = new Guid("8e5d72fd-4702-4428-abd9-9c3f8bd7801a"), Achternaam = "Mega", ClubId = new Guid("cabaf72e-c69e-456b-8da9-d2c9aac86ff0"), Email = "Mega@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Mindy" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.ClubSupporter", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Club")
                        .WithMany("ClubSupporters")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SuperCyclingWorld.Core.Entities.Supporter")
                        .WithMany("Clubs")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.FanRegistratie", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Supporter")
                        .WithMany("Wielrenners")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner")
                        .WithMany("Wielrenners")
                        .HasForeignKey("WielrennerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Fiets", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner")
                        .WithMany("Fietsen")
                        .HasForeignKey("WielrennerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Wielrenner", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Club", "Club")
                        .WithMany("Leden")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
