// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialCyclingWorld.Web.Data;

namespace SuperCyclingWorld.Web.Migrations
{
    [DbContext(typeof(SCWDbContext))]
    [Migration("20210710115455_RandomClubOfWielrenners")]
    partial class RandomClubOfWielrenners
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("Clubleider");

                    b.Property<string>("Clubnaam");

                    b.HasKey("Id");

                    b.ToTable("Clubs");

                    b.HasData(
                        new { Id = new Guid("00bf9430-e1cb-45f5-beac-8660eb34ec2d"), Clubnaam = "WTC" },
                        new { Id = new Guid("bb7f1996-516a-4419-b46d-c11b3ecc4cbd"), Clubnaam = "DCTV" },
                        new { Id = new Guid("d336dfe2-36f1-42c6-988c-f878ece07c9e"), Clubnaam = "De lustige rijders" },
                        new { Id = new Guid("ed952d83-e788-4c66-bf85-0143859f120b"), Clubnaam = "WTC Melsele" },
                        new { Id = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Clubnaam = "The master cyclists" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.ClubSupporter", b =>
                {
                    b.Property<Guid>("ClubId");

                    b.Property<Guid>("SupporterId");

                    b.HasKey("ClubId", "SupporterId");

                    b.HasIndex("SupporterId");

                    b.ToTable("ClubSupporter");

                    b.HasData(
                        new { ClubId = new Guid("d336dfe2-36f1-42c6-988c-f878ece07c9e"), SupporterId = new Guid("583d618d-1bd8-46b1-8369-723dbf29d126") },
                        new { ClubId = new Guid("00bf9430-e1cb-45f5-beac-8660eb34ec2d"), SupporterId = new Guid("3142f58f-ced4-43f2-9695-861a715d8ed0") },
                        new { ClubId = new Guid("bb7f1996-516a-4419-b46d-c11b3ecc4cbd"), SupporterId = new Guid("2bf72cb3-08f3-4b6e-b449-6beee971776e") },
                        new { ClubId = new Guid("d336dfe2-36f1-42c6-988c-f878ece07c9e"), SupporterId = new Guid("5d35f628-12db-42b7-ac20-feb62d7b5d74") },
                        new { ClubId = new Guid("00bf9430-e1cb-45f5-beac-8660eb34ec2d"), SupporterId = new Guid("583d618d-1bd8-46b1-8369-723dbf29d126") },
                        new { ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), SupporterId = new Guid("5d35f628-12db-42b7-ac20-feb62d7b5d74") },
                        new { ClubId = new Guid("ed952d83-e788-4c66-bf85-0143859f120b"), SupporterId = new Guid("3142f58f-ced4-43f2-9695-861a715d8ed0") },
                        new { ClubId = new Guid("00bf9430-e1cb-45f5-beac-8660eb34ec2d"), SupporterId = new Guid("2bf72cb3-08f3-4b6e-b449-6beee971776e") }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.FanRegistratie", b =>
                {
                    b.Property<Guid>("SupporterId");

                    b.Property<Guid>("WielrennerId");

                    b.HasKey("SupporterId", "WielrennerId");

                    b.HasIndex("WielrennerId");

                    b.ToTable("FanRegistratie");

                    b.HasData(
                        new { SupporterId = new Guid("3142f58f-ced4-43f2-9695-861a715d8ed0"), WielrennerId = new Guid("31083c41-4e2a-4559-8341-eb64e8ebbd2b") },
                        new { SupporterId = new Guid("5d35f628-12db-42b7-ac20-feb62d7b5d74"), WielrennerId = new Guid("47f609cf-f40f-425d-883d-3762592c3ea5") },
                        new { SupporterId = new Guid("3142f58f-ced4-43f2-9695-861a715d8ed0"), WielrennerId = new Guid("95897512-6814-4fff-b33f-0d74f001681b") },
                        new { SupporterId = new Guid("583d618d-1bd8-46b1-8369-723dbf29d126"), WielrennerId = new Guid("31083c41-4e2a-4559-8341-eb64e8ebbd2b") },
                        new { SupporterId = new Guid("5d35f628-12db-42b7-ac20-feb62d7b5d74"), WielrennerId = new Guid("b98ab10a-e854-4ec2-a2bc-7f8b9cd9f99b") },
                        new { SupporterId = new Guid("2bf72cb3-08f3-4b6e-b449-6beee971776e"), WielrennerId = new Guid("47f609cf-f40f-425d-883d-3762592c3ea5") }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Fiets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Merk");

                    b.Property<Guid>("WielrennerId");

                    b.Property<string>("Zadel");

                    b.HasKey("Id");

                    b.HasIndex("WielrennerId");

                    b.ToTable("Fietsen");

                    b.HasData(
                        new { Id = new Guid("8f68ef89-791f-4a9c-88bd-8e5368f99c9d"), Merk = "B-Twin", WielrennerId = new Guid("31083c41-4e2a-4559-8341-eb64e8ebbd2b"), Zadel = "Zwart zadel" },
                        new { Id = new Guid("5f57e9b1-7286-4656-81a8-6912323d9760"), Merk = "Moldava", WielrennerId = new Guid("95897512-6814-4fff-b33f-0d74f001681b"), Zadel = "Geel zadel" },
                        new { Id = new Guid("1a06bdfb-eec7-4fad-9d0c-b740130cc0e6"), Merk = "Merckx", WielrennerId = new Guid("b98ab10a-e854-4ec2-a2bc-7f8b9cd9f99b"), Zadel = "Oranje zadel" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Supporter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Achternaam");

                    b.Property<string>("Email");

                    b.Property<DateTime>("GeboorteDatum");

                    b.Property<string>("Paswoord");

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.ToTable("Supporters");

                    b.HasData(
                        new { Id = new Guid("3142f58f-ced4-43f2-9695-861a715d8ed0"), Achternaam = "The Pooh", Email = "ThePooh@live.be", GeboorteDatum = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Winnie" },
                        new { Id = new Guid("583d618d-1bd8-46b1-8369-723dbf29d126"), Achternaam = "Van Achtmaal", Email = "VanAchtmaal@live.be", GeboorteDatum = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Thomas" },
                        new { Id = new Guid("2bf72cb3-08f3-4b6e-b449-6beee971776e"), Achternaam = "VanKerkhove", Email = "VanKerkhove@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Nico" },
                        new { Id = new Guid("5d35f628-12db-42b7-ac20-feb62d7b5d74"), Achternaam = "Kronenburg", Email = "Kronenburg@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Koen" },
                        new { Id = new Guid("ade6b0ec-e8f8-4ed8-a14a-b79f65018061"), Achternaam = "Van Kruisem", Email = "VanKruisem@live.be", GeboorteDatum = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Willy" },
                        new { Id = new Guid("a970a7e8-1270-441d-9a8d-41a1939c654c"), Achternaam = "Wezemaal", Email = "Wezemaal@live.be", GeboorteDatum = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Bert" },
                        new { Id = new Guid("d7205a08-e69e-4a74-8981-1c956ea2635e"), Achternaam = "Opdorp", Email = "Opdorp@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Alfons" },
                        new { Id = new Guid("89aee80e-f503-42a1-9034-92017c2389be"), Achternaam = "AppelGate", Email = "Appelgate@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Christina" },
                        new { Id = new Guid("01545422-6a34-4feb-8df6-ab1c76cd84c1"), Achternaam = "Monroe", Email = "Monroe@live.be", GeboorteDatum = new DateTime(2009, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Marlyn" },
                        new { Id = new Guid("fa4c28f2-1ddd-4a19-8286-ca4b5d99b99b"), Achternaam = "Clooney", Email = "Clooney@live.be", GeboorteDatum = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "George" },
                        new { Id = new Guid("3efb3bd3-77ac-41be-9b68-76df2f0313dd"), Achternaam = "Peeters", Email = "Peeters@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Jan" },
                        new { Id = new Guid("d8f01dcc-a562-433e-90bf-d74fb6905b7d"), Achternaam = "Reyns", Email = "Reyns@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Rita" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Wielrenner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Achternaam");

                    b.Property<Guid?>("ClubId")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<DateTime>("GeboorteDatum");

                    b.Property<string>("Paswoord");

                    b.Property<string>("Voornaam");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Wielrenners");

                    b.HasData(
                        new { Id = new Guid("b98ab10a-e854-4ec2-a2bc-7f8b9cd9f99b"), Achternaam = "Franckaert", ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Email = "Franckaert@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Robin" },
                        new { Id = new Guid("31083c41-4e2a-4559-8341-eb64e8ebbd2b"), Achternaam = "Jansma", ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Email = "Jansma@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Johanna" },
                        new { Id = new Guid("95897512-6814-4fff-b33f-0d74f001681b"), Achternaam = "Vissers", ClubId = new Guid("00bf9430-e1cb-45f5-beac-8660eb34ec2d"), Email = "Vissers@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Bert" },
                        new { Id = new Guid("47f609cf-f40f-425d-883d-3762592c3ea5"), Achternaam = "Depardieu", ClubId = new Guid("d336dfe2-36f1-42c6-988c-f878ece07c9e"), Email = "Depardieu@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Gerard" },
                        new { Id = new Guid("88454017-8023-4d00-a86e-7ecd7d899a6d"), Achternaam = "Van Overmeire", ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Email = "VanOvermeire@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Marc" },
                        new { Id = new Guid("9bfdc1a1-c9ba-4f0e-b9c5-9eda2a9b8604"), Achternaam = "Camara", ClubId = new Guid("ed952d83-e788-4c66-bf85-0143859f120b"), Email = "Camara@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Herdy" },
                        new { Id = new Guid("c2fe08ab-3fa2-4793-a815-78bba06d0166"), Achternaam = "Donckerwolcke", ClubId = new Guid("00bf9430-e1cb-45f5-beac-8660eb34ec2d"), Email = "Donckerwolcke@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Thomas" },
                        new { Id = new Guid("cf9a1ddd-3b10-44e9-a925-f15b0f50de2a"), Achternaam = "Garnaal", ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Email = "Garnaal@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Sofie" },
                        new { Id = new Guid("0ee2f749-ac44-4881-8132-1fea359b7815"), Achternaam = "Brokkenpap", ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Email = "Brokkenpap@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Berend" },
                        new { Id = new Guid("375c24c2-2366-4f3d-b7f2-d52319c97ea7"), Achternaam = "Mega", ClubId = new Guid("00bf9430-e1cb-45f5-beac-8660eb34ec2d"), Email = "Mega@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Mindy" },
                        new { Id = new Guid("5f25879c-79a5-46f4-91fd-66358dbb2399"), Achternaam = "Scarlet", ClubId = new Guid("ed952d83-e788-4c66-bf85-0143859f120b"), Email = "Scarlet@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Johanson" },
                        new { Id = new Guid("b43cb09c-371e-4ce4-95ed-b627413c5772"), Achternaam = "Beukelaer", ClubId = new Guid("bb7f1996-516a-4419-b46d-c11b3ecc4cbd"), Email = "Beukelaer@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Koekjes" },
                        new { Id = new Guid("98a923b2-1abb-4bcb-9d3e-4c1bbb74994c"), Achternaam = "Mertens", ClubId = new Guid("bb7f1996-516a-4419-b46d-c11b3ecc4cbd"), Email = "Mertens@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Evelyne" },
                        new { Id = new Guid("a7d44fa5-bcdf-4986-8910-2062f2105a0b"), Achternaam = "VanHoof", ClubId = new Guid("d336dfe2-36f1-42c6-988c-f878ece07c9e"), Email = "Vanhoof@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Emily" },
                        new { Id = new Guid("bf7b1648-f1f7-42d3-a15d-ce89eac2ebfd"), Achternaam = "Vanderplas", ClubId = new Guid("bb7f1996-516a-4419-b46d-c11b3ecc4cbd"), Email = "Vanderplas@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Sonja" },
                        new { Id = new Guid("45dfe8d8-0c55-4e98-b840-afa7d5df042d"), Achternaam = "Bambino", ClubId = new Guid("d336dfe2-36f1-42c6-988c-f878ece07c9e"), Email = "Bambino@live.be", GeboorteDatum = new DateTime(1981, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Salvatore" },
                        new { Id = new Guid("1d5cc85c-1cff-4a07-9e6f-7a22da6edf61"), Achternaam = "Zalinski", ClubId = new Guid("bb7f1996-516a-4419-b46d-c11b3ecc4cbd"), Email = "Zalinski@live.be", GeboorteDatum = new DateTime(1985, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Wosznjeck" },
                        new { Id = new Guid("8f7b22c4-b9b9-47c5-b07a-c0f38654b533"), Achternaam = "Debruyne", ClubId = new Guid("bb7f1996-516a-4419-b46d-c11b3ecc4cbd"), Email = "Debruyne@live.be", GeboorteDatum = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Kevin" },
                        new { Id = new Guid("aa18a2c0-f08a-40e4-83e2-9b3188c54bce"), Achternaam = "Hazard", ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Email = "Hazard@live.be", GeboorteDatum = new DateTime(1999, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Eden" },
                        new { Id = new Guid("b5486b98-1944-45a7-9838-cdb7758aa807"), Achternaam = "Evenepoel", ClubId = new Guid("34f81176-2917-42c3-b518-8b02bb8be713"), Email = "Evenepoel@live.be", GeboorteDatum = new DateTime(1979, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Paswoord = "202CB962AC59075B964B07152D234B70", Voornaam = "Remco" }
                    );
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.ClubSupporter", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Club")
                        .WithMany("ClubSupporters")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SuperCyclingWorld.Core.Entities.Supporter")
                        .WithMany("Clubs")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.FanRegistratie", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Supporter")
                        .WithMany("Wielrenners")
                        .HasForeignKey("SupporterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner")
                        .WithMany("Wielrenners")
                        .HasForeignKey("WielrennerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Fiets", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Wielrenner")
                        .WithMany("Fietsen")
                        .HasForeignKey("WielrennerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SuperCyclingWorld.Core.Entities.Wielrenner", b =>
                {
                    b.HasOne("SuperCyclingWorld.Core.Entities.Club", "Club")
                        .WithMany("Leden")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
